from odoo import models, fields

class HrAttendance(models.Model):
    _inherit = "hr.attendance"

    generated_by_system = fields.Boolean(string="Generated by System",
                                         default=False, readonly=True,
                                         help="Mark if this attendance record was generated by the simulation")
    
